http:
  services:
    proxy-dashboard:
      loadBalancer:
        servers:
          - url: "http://localhost:8080"
        passHostHeader: true
    docker-dashboard:
      loadBalancer:
        servers:
          - url: "http://localhost:9000"
        passHostHeader: true
    frontend-dev-server:
      loadBalancer:
        servers:
          - url: "http://localhost:4001"
        passHostHeader: true
    backend-dev-server:
      loadBalancer:
        servers:
          - url: "http://localhost:4002"
        passHostHeader: true
    frontend-server:
      loadBalancer:
        servers:
          - url: "http://localhost:4003"
        passHostHeader: true
    backend-server:
      loadBalancer:
        servers:
          - url: "http://localhost:4004"
        passHostHeader: true
    frontend-integration-server:
      loadBalancer:
        servers:
          - url: "http://localhost:4005"
        passHostHeader: true
    backend-integration-server:
      loadBalancer:
        servers:
          - url: "http://localhost:4006"
        passHostHeader: true
    file-server:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"
        passHostHeader: true
    dummy-service:
      loadBalancer:
        servers:
          - url: "http://uspray.kr"

  routers:
    proxy-dashboard-router:
      rule: "Host(`proxy.uspray.kr`)"
      service: proxy-dashboard
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    docker-dashboard-router:
      rule: "Host(`docker.uspray.kr`)"
      service: docker-dashboard
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    frontend-dev-server-router:
      rule: "Host(`www.dev.uspray.kr`)"
      service: frontend-dev-server
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    backend-dev-server-router:
      rule: "Host(`api.dev.uspray.kr`)"
      service: backend-dev-server
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    frontend-server-router:
      rule: "Host(`www.uspray.kr`)"
      service: frontend-server
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    backend-server-router:
      rule: "Host(`api.uspray.kr`)"
      service: backend-server
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    frontend-integration-server-router:
      rule: "Host(`www.intg.uspray.kr`)"
      service: frontend-integration-server
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    backend-integration-server-router:
      rule: "Host(`api.intg.uspray.kr`)"
      service: backend-integration-server
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    file-server-router:
      rule: "PathPrefix(`/.well-known`)"
      service: file-server
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      priority: 1000
    github-router:
      rule: "Host(`github.uspray.kr`)"
      middlewares: github
      service: dummy-service
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    
  middlewares:
    github:
      RedirectRegex:
        regex: "^https:\\/\\/github\\.uspray\\.kr(?:\\/.*)?$"
        replacement: "https://github.com/PrayHelper"
        permanent: true
